const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.Fade,
		C3.Plugins.Json,
		C3.Behaviors.Timer,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Plugins.Particles,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.AJAX,
		C3.Plugins.Browser,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Plugins.Dictionary,
		C3.Plugins.TelegramMiniAppsSDK,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.AdvancedRandom.Acts.CreateProbabilityTable,
		C3.Plugins.AdvancedRandom.Acts.AddProbabilityEntry,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Json.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Json.Exps.CurrentKey,
		C3.Plugins.Sprite.Acts.LoadFromJsonString,
		C3.Plugins.Json.Exps.GetAsBeautifiedString,
		C3.Plugins.Json.Exps.Path,
		C3.Plugins.Json.Cnds.HasKey,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Cnds.PickTopBottom,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Json.Acts.DeleteKey,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Json.Acts.SetJSON,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Exps.AsJSON,
		C3.Plugins.TelegramMiniAppsSDK.Acts.CloudStorageSetItem,
		C3.Plugins.Json.Exps.ToBeautifiedString,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Cnds.LayerEmpty,
		C3.Plugins.Touch.Exps.TouchID,
		C3.Plugins.Touch.Exps.YForID,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Acts.RemoveChild,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Exps.XForID,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.System.Cnds.LayerInteractive,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.AdvancedRandom.Exps.Weighted,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.Dictionary.Cnds.CompareValue,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Dictionary.Acts.SetKey,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.LocalStorage.Acts.RemoveItem,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.Text.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Exps.AnimationFrameTag,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.TelegramMiniAppsSDK.Exps.CloudStorageValue,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.Browser.Exps.Language,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Cnds.OnError,
		C3.Plugins.System.Cnds.TriggerOnce
	];
};
self.C3_JsPropNameTable = [
	{Physics: 0},
	{border: 0},
	{drop: 0},
	{Fade: 0},
	{gameObject: 0},
	{saveGameObjectJSON: 0},
	{Timer: 0},
	{Tween: 0},
	{spawner: 0},
	{pole: 0},
	{TiledBackground: 0},
	{Particles: 0},
	{AdvancedRandom: 0},
	{particle2: 0},
	{Particles2: 0},
	{gameOver: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{AJAX: 0},
	{Browser: 0},
	{type: 0},
	{Anchor: 0},
	{buttons: 0},
	{buttonIcon: 0},
	{lang: 0},
	{Text: 0},
	{popUp: 0},
	{testText: 0},
	{Dictionary: 0},
	{languageJSON: 0},
	{cursor: 0},
	{LoadingBar_Back: 0},
	{LoadingBar_Top: 0},
	{TelegramMiniAppsSDK: 0},
	{gameObjectFam: 0},
	{touchID: 0},
	{start: 0},
	{create: 0},
	{score: 0},
	{addScore: 0},
	{touchID2: 0},
	{size: 0},
	{bestScore: 0},
	{music: 0},
	{sound: 0},
	{musicName: 0},
	{vol: 0},
	{tag: 0},
	{soundName: 0},
	{key: 0},
	{var: 0},
	{varStr: 0},
	{getData: 0},
	{getData2: 0},
	{loading_progress: 0},
	{maxLoading_progress: 0},
	{language: 0},
	{reward: 0}
];

self.InstanceType = {
	border: class extends self.ISpriteInstance {},
	gameObject: class extends self.ISpriteInstance {},
	saveGameObjectJSON: class extends self.IJSONInstance {},
	spawner: class extends self.ISpriteInstance {},
	pole: class extends self.ITiledBackgroundInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Particles: class extends self.IParticlesInstance {},
	AdvancedRandom: class extends self.IInstance {},
	particle2: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	gameOver: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	buttons: class extends self.ISpriteInstance {},
	buttonIcon: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	popUp: class extends self.ISpriteInstance {},
	testText: class extends self.ITextInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	languageJSON: class extends self.IJSONInstance {},
	cursor: class extends self.ISpriteInstance {},
	LoadingBar_Back: class extends self.ITiledBackgroundInstance {},
	LoadingBar_Top: class extends self.ITiledBackgroundInstance {},
	TelegramMiniAppsSDK: class extends self.C3.Plugins.TelegramMiniAppsSDK.Instance {},
	gameObjectFam: class extends self.ISpriteInstance {}
}